#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT_DIR"

if command -v cloudflared >/dev/null 2>&1; then
  CF_BIN="$(command -v cloudflared)"
else
  "$ROOT_DIR/nexus_control_server/scripts/install_cloudflared_wsl.sh"
  CF_BIN="$ROOT_DIR/nexus_control_server/bin/cloudflared"
fi

TUNNEL_NAME="${NEXUS_TUNNEL_NAME:-nexus-control}"
TUNNEL_HOSTNAME="${NEXUS_TUNNEL_HOSTNAME:-}"
PORT="${NEXUS_CONTROL_PORT:-8787}"

if [[ -z "$TUNNEL_HOSTNAME" ]]; then
  echo "Set NEXUS_TUNNEL_HOSTNAME (ex: nexus-control.seudominio.com)"
  exit 1
fi

echo "1) Cloudflare login (interactive browser auth)..."
"$CF_BIN" tunnel login

echo "2) Creating tunnel (or using existing)..."
if ! "$CF_BIN" tunnel list | grep -q "$TUNNEL_NAME"; then
  "$CF_BIN" tunnel create "$TUNNEL_NAME"
else
  echo "Tunnel '$TUNNEL_NAME' already exists."
fi

echo "3) Routing DNS hostname to tunnel..."
"$CF_BIN" tunnel route dns "$TUNNEL_NAME" "$TUNNEL_HOSTNAME"

echo "4) Creating config file..."
mkdir -p "$HOME/.cloudflared"
CRED_FILE="$(ls -1 "$HOME/.cloudflared"/*.json | head -n1)"
if [[ -z "${CRED_FILE:-}" ]]; then
  echo "Could not find tunnel credentials JSON in ~/.cloudflared"
  exit 1
fi

cat > "$HOME/.cloudflared/config.yml" <<EOF
# Generated by NEXUS setup script
tunnel: $TUNNEL_NAME
credentials-file: $CRED_FILE
ingress:
  - hostname: $TUNNEL_HOSTNAME
    service: http://127.0.0.1:$PORT
  - service: http_status:404
EOF

echo "Done."
echo "Next: start your server and run:"
echo "  cloudflared tunnel --config ~/.cloudflared/config.yml run $TUNNEL_NAME"
